### ISSUE TITLE
API or function to send inter processor interrupt 

### ISSUE THREAD

**Issue by xiaolongwu01** [Bareflank/MicroV#19]
Does MicroV microkernel  run on one CPU core or multi core?
Could you help pointing out to me the API or function for sending IPI or INIT interrupt in MicroV?
Thanks.

**Comment by connojd** [comment]
The mono branch of MicroV supports IPIs. An example of a shootdown IPI can be found here: https://github.com/Bareflank/MicroV/blob/mono/vmm/src/hve/arch/intel_x64/vcpu.cpp#L631

The code that actually writes to the local apic is here: https://github.com/Bareflank/MicroV/blob/mono/vmm/src/hve/arch/intel_x64/apic/lapic.cpp#L201

**Comment by xiaolongwu01** [comment]
Thank you very much, Connor, this is very helpful to me.
By the way, since currently I am exploring the early booting of Bareflank, could I ask which file contain the booting code of VMM (not late launch), and which code file is for booting the OS(I mean the code for booting host OS from VMM, not the userspace tool such as uvctl for booting guest VMs ).

**Comment by rianquinn** [comment]
@xiaolongwu01 The boot code is in the Bareflank/hypervisor for the old stuff. It is scattered between INIT/SIPI, control registers, EPT and MSRs. 
https://github.com/Bareflank/hypervisor/tree/d2203d8fa44339e1c7dd0ce8264f5248b43a7648/bfvmm/src/hve/arch/intel_x64/vmexit

**Comment by xiaolongwu01** [comment]
Ok, Thanks! I guess the code file you send is for booting VM (OS)(my second question), right? Do you know which file is about booting VMM (I am talking about early booting that the VMM is booting from boot loader or EFI, then there must be a starting point in VMM to boot up either on one CPU core or Multi-core.)

**Comment by connojd** [comment]
@xiaolongwu01 That is done with the EFI loader found here: https://github.com/Bareflank/MicroV/blob/mono/deps/hypervisor/bfdriver/src/platform/efi/entry.c

The EFI loader calls into the common driver code here:
https://github.com/Bareflank/MicroV/blob/mono/deps/hypervisor/bfdriver/src/common.c

which in turn loads the VMM and calls into the VMM's ELF binary to perform initialization.
The entry point into the VMM C++ code called by the loader is here: 
https://github.com/Bareflank/MicroV/blob/mono/deps/hypervisor/bfvmm/src/entry/entry.cpp#L182

This initialization is performed on each core, but instead of using IPIs directly, the StartupThisAp
function from MP services is used here:
https://github.com/Bareflank/MicroV/blob/mono/deps/hypervisor/bfdriver/src/platform/efi/platform.c#L201

Eventually these calls result in VT-x being turned on and the driver context (EFI in this case)
being lifted into a VM. Then the driver code invokes a special cpuid leaf, causing an exit
into the VMM (that is running in VMX root at this point) so that the VMM can perform
further initialization with its own CR3 as needed.
This cpuid leaf is invoked here: 
https://github.com/Bareflank/MicroV/blob/mono/deps/hypervisor/bfvmm/src/entry/entry.cpp#L154

and the corresponding handler is here:
https://github.com/Bareflank/MicroV/blob/mono/vmm/src/hve/arch/intel_x64/vcpu.cpp#L536

**Comment by xiaolongwu01** [comment]
Thank you very much, Connor. I am totally clear about it now.
