### ISSUE TITLE
Incorrect guest support info in README

### ISSUE THREAD

**Issue by iggy** [Bareflank/MicroV#25]
Both Xen and KVM (various userspaces) support Windows guests and KVM(Qemu) supports MacOS. KVM/Qemu supports a ton of other guests.

**Comment by rianquinn** [comment]
When we say that KVM and Xen do not support Windows, we are talking about the root VM. From a Xen point of view, this would be Dom0. From a KVM point of view, this would be the host itself (since KVM runs in a Linux driver, in KVM's case, Linux is the hypervisor). 

The following wiki tracks our progress towards getting KVM's APIs to work with MicroV in the master branch. For now we are focusing on Linux in the root VM, but Windows is next. 
https://github.com/Bareflank/MicroV/wiki/KVM-API-Integration

In our Mono branch we implemented the Xen ABI, and it only supports Windows at the moment, so in Mono's case we only support a Windows dom0. 

With respect to Windows guest VMs, yes both Xen and KVM (and pretty much every other hypervisor out there) not only supports Windows and Linux, but several other OSs as well.

**Comment by iggy** [comment]
Gotcha. The part of the README I was looking at mentions guest right before that, so I mistook what was being talked about there. Thanks for the quick clarification. This looks like a fun project that I'm keeping my eyes on.
