### ISSUE TITLE
KVM_SET_USER_MEMORY_REGION

### ISSUE THREAD

**Issue by rithesh7** [Bareflank/MicroV#32]
For KVM_SET_USER_MEMORY_REGION the following changes are needed 

-->In microv/shim/include  kvm_userspace_memory_region.h
->Changing the struct in the kvm_userspace_memory_region file with the following struct as explained in WIKI
`struct kvm_userspace_memory_region
{
    uint32_t slot;
    uint32_t flags;
    uint64_t guest_phys_addr;
    uint64_t memory_size; /* bytes */
	uint64_t userspace_addr; /* start of the userspace allocated memory */ 
};`

-->In microv/shim/linux/src entry .c
->Include the  handle_vm_kvm_set_user_memory_region.c file 
->Modify the dispatch_vm_kvm_set_user_memory_region by including the copy from user(to get the user memory) and calling the handle file with the user memory.

```
static long
dispatch_vm_kvm_set_user_memory_region(
    struct kvm_userspace_memory_region *const ioctl_args)
{
    struct kvm_userspace_memory_region kvm_userspace_mem;
	
	if(copy_from_user(&kvm_userspace_mem, ioctl_args ,sizeof(kvm_userspace_mem)))
	{
		bferror("copy_from_user failed");
		return -EFAULT;
	}
	
	if(handle_vm_kvm_set_user_memory_region(&kvm_userspace_mem))
	{
		bferror("handle_vm_kvm_set_user_memory_region failed");
        return -EFAULT;
	}
    return 1;
}
```

-->In microv/shim/src handle file handle_vm_kvm_set_user_memory_region.c
->Include the g_hndl.h,  platform.h, and mv_hypercall.h files.
->mutex_lock -  to lock memory and used to take a userspace buffer of memory and tell the kernel that it cannot be paged out.
->Divide the user memory to 4k pages, find number of 4K pages required for the user memory (Memory size?)
->loop to load the user memory using the no. of pages as count for loop to end(how is the lock implemented in the project ? )
      > Can get the Physical address from using platform_virt_to_phys() from platform.c ?
      > Create new header to define the mv_mdl_entry_t & mv_mdl_t. Use these mdls to store the pages of the memory
[https://github.com/Bareflank/MicroV/blob/master/docs/MicroV%20Hypercall%20Specification.md#1-introduction](url)  1.4.5
      > When memory is full it reaches MV_MDL_MAX_ENTRIES (When the loop ends should I consider that the memory is completly transfered or is there any parameter to notify this ? ) 
      > Call mv_vm_op_mmio_map when memory is full or loop ends to stored the memory
->mutex unlock (Should we create a platform lock and platform_unlock functions or use existing once from online?)
->return shim success

```
int64_t
handle_vm_kvm_set_user_memory_region(struct kvm_userspace_memory_region *const ioctl_args)
{
    platform_expects(MV_INVALID_HANDLE != g_hndl);
    platform_expects(NULL != ioctl_args);
	
	mutex_lock(ioctl_args->userspace_addr);
	//platform_lock_mem(ioctl_args->userspace_addr,ioctl_args->memory_size);
	
	//to find number of 4k pages required for requested user memory_size
	int no_of_pages = ((ioctl_args->memory_size)/(1<<4)); 
	
	for(loop=0; loop < no_of_pages; loop ++)
	{
		//-get phys address                              - need to identify 
		//-fill in mv_mdl_entry_t in mv_mdl_t   - need to identify 
		//-if mv_mdl_t is full or done                - need to identify 
		 struct kvm_userspace_memory_region* kvm_userspace_mem = mv_vm_op_mmio_map(g_hndl);
		 platform_memcpy(ioctl_args, kvm_userspace_mem, sizeof(ioctl_args));
		 ioctl_args->userspace_addr = kvm_userspace_mem->userspace_addr;
	}
	
	mutex_unlock(ioctl_args->userspace_addr);
	//platform_unlock_mem(ioctl_args->userspace_addr,ioctl_args->memory_size);

    return SHIM_SUCCESS;
}
```
`

**Comment by rianquinn** [comment]
@chp-io Thoughts?

**Comment by chp-io** [comment]
**In microv/shim/linux/src entry.c**:

Please refer to [Rian's feedback](https://github.com/Bareflank/MicroV/pull/30/files#r706554387) for the kvm naming scheme. TLDR:  replace `kvm_userspace_mem` with `args`.

**For handle_vm_kvm_set_user_memory_region.c**:

> mutex_lock - to lock memory and used to take a userspace buffer of memory and tell the kernel that it cannot be paged out.

When we say that the memory region provided by userspace cannot be paged out, we mean for its entire lifetime, not just during this function call. Locking, in this context, means to be locked in memory and it can never be paged out to disk.

Possible candidates:
- mlock (take a look at the syscall handler)
- `pin_user_pages` and related calls seem to be good candidates

Regarding locking Linux kernel data structures in the shim, I would do it the same way KVM does.

> "Can get the Physical address from using platform_virt_to_phys() from platform.c ?"

Maybe. c.f. 4th bullet in KVM_SET_USER_MEMORY_REGION's description from the [wiki](https://github.com/Bareflank/MicroV/wiki/KVM-API-Integration#step-1-quick-demo).
I would look at the KVM driver.

> Create new header to define the mv_mdl_entry_t & mv_mdl_t. Use these mdls to store the pages of the memory
  //-fill in mv_mdl_entry_t in mv_mdl_t   - need to identify

You fill it via the `mv_vm_op_mmio_map` hypercall. The shim doesn't directly own the `mv_mdl_t` object, the hypervisor does and this hypercall is used to interact with it.

Please make sure to read [mv_vm_op_mmio_map's specification](https://github.com/Bareflank/MicroV/blob/master/docs/MicroV%20Hypercall%20Specification.md#2138-mv_vm_op_mmio_map-op0x4-idx0x7) in order to use it properly. This hypercall can take a long time to process, therefore it has a "continuation" capability, so multiple calls to it with the same arguments may be necessary to complete. You will need to check the return status for `MV_STATUS_RETRY_CONTINUATION`. You can read more about the [hypercall continuation](https://github.com/Bareflank/MicroV/blob/master/docs/MicroV%20Hypercall%20Specification.md#28-hypercall-continuation).

**Comment by rianquinn** [comment]
> Memory size?

This should be `kvm_userspace_memory_region::memory_size`, 

> mutex_lock 

Like @chp-io stated, when we say lock memory, we mean that the memory cannot be paged out. In userspace, you would use this:
https://linux.die.net/man/2/mlock

We need to determine what the "kernel" version of this API is. KVM's driver should have this code, so I would take a look and see how they did this. DO NOT copy paste any code from KVM as we use MIT and not GPL, so we cannot use KVM's code in any way, but there is nothing wrong with at least learning how they attempted to solve some of these issues in the kernel. 

We will need a mutex lock in the shim for this IOCTL however. Specifically, modifying the slots for a VM can happen from an PP, which means that we must mutex lock modifications to the VM structure. We actually have this issue with VCPU allocation as well, so I will add the mutex APIs and you can use them for this as well. We may just leave the mutex logic in the dispatch functions for now, but I need to think about that more. 

> platform_virt_to_phys

Actually yes, I think you can use this. This function only works for vmalloc memory. Most userspace memory is allocated using vmalloc and friends, so I think this may actually work. For now, assume this is the case, and we will know pretty quickly, so if it isn't we can wort this out later. 

> Create new header to define the mv_mdl_entry_t & mv_mdl_t.

Nope, it is already done for you. Update your repro and you will see it there. 

> When memory is full it reaches MV_MDL_MAX_ENTRIES (When the loop ends should I consider that the memory is completly transfered or is there any parameter to notify this ? )

No. This part of your algorithm needs more attention. I'm not going to solve it here for you as this really is the hard part of this function. Please update your RFC to include the details of how this is going to work assuming the following
```
/** IOCTL #1 */
struct kvm_userspace_memory_region 
{ 
    uint32_t slot = 0; 
    uint32_t flags = READ_WRITE_EXECUTE; 
    uint64_t guest_phys_addr = 0x1000; 
    uint64_t memory_size = 8GB; 
    uint64_t userspace_addr = 0x40000; 
}

/** IOCTL #2 */
struct kvm_userspace_memory_region 
{ 
    uint32_t slot = 1; 
    uint32_t flags = READ_WRITE; 
    uint64_t guest_phys_addr = 0xF000000001000; 
    uint64_t memory_size = 2M; 
    uint64_t userspace_addr = 0x20000; 
}
```

Hints:
- You will have to call `mv_vm_op_mmio_map` more than once
- You need to manage the slots. This will require slot storage to be added to shim_vm_t. This is the thing that needs to be mutex locked.
